# Generated by Django 5.2.1 on 2025-06-02 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('detection_id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_date', models.DateField()),
                ('detection_time', models.TimeField()),
                ('detections', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='camera.camera')),
            ],
            options={
                'db_table': 'detections',
                'ordering': ['-detection_date', '-detection_time'],
            },
        ),
    ]
