# Generated by Django 5.2.2 on 2025-08-24 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_detection'),
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_detections', to='camera.camera'),
        ),
        migrations.AlterModelTable(
            name='detection',
            table='monitoring_detections',
        ),
    ]
